name: Rust CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  check:
    name: Check, Format, Clippy, and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, nightly]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-all-features
        run: cargo install --git https://github.com/sabify/cargo-all-features
      - name: Clippy with all feature combinations
        run: cargo all-features clippy -- -D warnings
      - name: Test with all feature combinations (without docs)
        run: cargo all-features test -- --lib --examples --tests --benches
      - name: Test with all features and all targets
        run: cargo test --all-features --all-targets
      - name: Check code formatting
        run: cargo build --all-features && cargo fmt --all -- --check
