name: Update Data
on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write
jobs:
  update-currencies:
    runs-on: ubuntu-latest
    env:
      CURRENCIES_PATH: "data/currencies.csv"
      CURRENCIES_URL: "https://datahub.io/core/currency-codes/_r/-/data/codes-all.csv"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download and replace currencies.csv file
        run: |
          set -xe
          curl -L -o $CURRENCIES_PATH "$CURRENCIES_URL"
          echo "CSV file downloaded and replaced"
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code --quiet $CURRENCIES_PATH || echo "changes=true" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update currencies data [automated]"
          title: "Update currencies data"
          body: |
            This PR updates the currencies data file with the latest version.

            - Auto-generated by the Update workflow
            - Source: ${{ env.CURRENCIES_URL }}
            - Updated: ${{ github.event.repository.updated_at }}
          branch: update-csv-data
          base: master
          delete-branch: true
  update-countries:
    runs-on: ubuntu-latest
    env:
      COUNTRIES_PATH: "countries"
      COUNTRIES_DATA_PATH: "lib/countries/data"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check new changes in data path
        id: git-check
        run: |
          set -xe

          git submodule init

          BEFORE_UPDATE=$(git submodule status)
          BEFORE_HASH=$(echo "$BEFORE_UPDATE" | grep "$COUNTRIES_PATH" | awk '{ print $1 }' | sed 's/^[-+]//g')

          git submodule update --remote --merge --recursive

          AFTER_UPDATE=$(git submodule status)
          AFTER_HASH=$(echo "$AFTER_UPDATE" | grep "$COUNTRIES_PATH" | awk '{ print $1 }' | sed 's/^[-+]//g')

          cd "$COUNTRIES_PATH"
          CHANGED_FILES=$(git diff --name-only "$BEFORE_HASH" "$AFTER_HASH" -- "$COUNTRIES_DATA_PATH")

          if [ -n "$CHANGED_FILES" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT

            echo "changed_files<<EOF" >> $GITHUB_OUTPUT
            echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update countries submodule [automated]"
          title: "Update countries submodule"
          body: |
            This PR updates the countries submodule with the latest version.

            Changed files:

            ```
            ${{ steps.git-check.outputs.changed_files }}
            ```

            - Auto-generated by the Update workflow
            - Updated: ${{ github.event.repository.updated_at }}
          branch: update-countries-submodule
          base: master
          delete-branch: true
